;Название секции где будет пункт | имя в меню | путь до модели | анимация | скорость анимации | флаг доступа
;Если требуется добавить в основное меню, в названии секции указать '_'
;Если флаг доступа не требуется указать '_'

Секси Танцы | Шпагат | models/animations_ground.mdl | 0 | 1.0 | _
Секси Танцы | Армия | models/animations_ground.mdl | 1 | 1.0 | _
Секси Танцы | Бёдра | models/animations_ground.mdl | 2 | 1.0 | _
Секси Танцы | Отвесный | models/animations_ground.mdl | 3 | 1.0 | _
Секси Танцы | Чир Лидерша | models/animations_ground.mdl | 4 | 0.5 | _
Секси Танцы | Мачо | models/animations_ground.mdl | 5 | 1.0 | _
Секси Танцы | Боец | models/animations_ground.mdl | 6 | 1.0 | _
Секси Танцы | Тверк | models/taunts.mdl | 21 | 1.0 | _

Танцы | Ква-Ква | models/animations_fix.mdl | 0 | 1.0 | _
Танцы | Пьяница | models/animations_fix.mdl | 1 | 1.0 | _
Танцы | Робот | models/animations_fix.mdl | 2 | 1.0 | _
Танцы | Рывки | models/animations_fix.mdl | 3 | 1.0 | _
Танцы | Отжимания | models/animations_fix.mdl | 8 | 1.0 | _
Танцы | Приветики | models/animations_fix.mdl | 11 | 1.0 | _
Танцы | Радостный | models/animations_fix.mdl | 12 | 1.0 | _
Танцы | Милота | models/animations_fix.mdl | 13 | 1.0 | _
Танцы | Поцелуйчики | models/animations_fix.mdl | 14 | 1.0 | _
Танцы | Кунг-Фу | models/animations_fix.mdl | 20 | 1.0 | _
Танцы | Калифорния | models/taunts.mdl | 13 | 1.0 | _
Танцы | Камель | models/taunts.mdl | 15 | 1.0 | _
Танцы | Русский Танец | models/taunts.mdl | 1 | 1.0 | _
Танцы | Аэробика | models/taunts.mdl | 2 | 1.0 | _
Танцы | Конга | models/taunts.mdl | 3 | 1.0 | _
Танцы | Гангам Стайл | models/taunts.mdl | 16 | 1.0 | _
Танцы | Макарена | models/taunts.mdl | 17 | 1.0 | _
Танцы | Скибиди | models/taunts.mdl | 19 | 1.0 | _
Танцы | Диджей | models/taunts.mdl | 20 | 1.0 | _
Танцы | Брейк | models/taunts.mdl | 22 | 1.0 | _

Позы | Поза | models/animations_fix.mdl | 15 | 1.0 | _
Позы | Стойка | models/animations_fix.mdl | 4 | 1.0 | _
Позы | Стул | models/animations_fix.mdl | 5 | 1.0 | _
Позы | Сидеть | models/animations_fix.mdl | 6 | 1.0 | _
Позы | Медитация | models/animations_fix.mdl | 7 | 1.0 | _
Позы | Кулак | models/animations_fix.mdl | 9 | 1.0 | _
Позы | Полежать | models/animations_fix.mdl | 10 | 1.0 | _
Позы | Заложник 1 | models/animations_fix.mdl | 16 | 1.0 | _
Позы | Заложник 2 | models/animations_fix.mdl | 17 | 1.0 | _
Позы | Заложник 3 | models/animations_fix.mdl | 21 | 1.0 | _
Позы | Фейс Контроль | models/animations_fix.mdl | 18 | 1.0 | _
Позы | Нет-Нет | models/animations_fix.mdl | 19 | 1.0 | _
Позы | Я туточки | models/animations_fix.mdl | 22 | 1.0 | _
Позы | Сдаюсь | models/animations_fix.mdl | 23 | 1.0 | _
Позы | Готов | models/taunts.mdl | 4 | 1.0 | _
Позы | Старт | models/taunts.mdl | 5 | 1.0 | _
Позы | Упал | models/taunts.mdl | 9 | 1.0 | _
Позы | Выпад | models/taunts.mdl | 11 | 1.0 | _
Позы | Поза 2 | models/taunts.mdl | 14 | 1.0 | _